kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: cau3
subjects:
  - kind: User
    name: k8s-readonly
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cau3
  name: pod-reader
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
